jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: ${JENKINS_ADMIN_ID}
         password: ${JENKINS_ADMIN_PASSWORD}
       - id: ${JENKINS_TRIGGER}
         password: ${JENKINS_TRIGGER_PASSWORD}
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
        - "Job/Build:authenticated"
  remotingSecurity:
    enabled: true
jobs:
  - script: >
      job('seed') {
        authenticationToken('${SEED_TRIGGER_TOKEN}')
        scm {
          git {
            remote {
              url 'https://github.com/sotcsa/zjenkins.git'
            }
          }
        }
        steps {
          jobDsl {
            targets 'src/jobs/*.groovy'
          }
        }
      }
security:
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: triggeringUsersAuthorizationStrategy
unclassified:
  location:
    url: ${BASE_URL}
