enkins_master:
  image: sotcsa/zjenkins
  container_name: zjenkins
  user: jenkins
  environment:
    - TZ=Europe/Budapest
    - JENKINS_ADMIN_ID=admin
    - JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD}
    - JENKINS_TRIGGER=trigger
    - JENKINS_TRIGGER_PASSWORD=${JENKINS_TRIGGER_PASSWORD}
    - SEED_TRIGGER_TOKEN=${SEED_TRIGGER_TOKEN}
    - BASE_URL=${BASE_URL}
  restart: always
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
    #- /var/jenkins_home:/var/jenkins_home
  ports:
    - 8095:8080
